### ISSUE TITLE
[스토리1] - 해야할 일 목록에 새로운 카드 추가

### ISSUE THREAD

**Issue by dlwnstjrzz** [dlwnstjrzz/todo-list#8]
## 구현하려는 기능
- [x] 유저는 [해야할 일] 목록에 새로운 할 일을 위해 카드를 추가한다.

### 1-1
- [x] [+] 추가 버튼을 누르면 새로운 카드를 등록할 수 있는 박스가 나온다.
  - [x] [+]를 누르면 카드입력화면이 하나만 생성돼야함.

### 1-2
- [x] [+]버튼을 다시 한 번 더 누르거나 취소 버튼을 누르면, 박스가 사라진다. 
  - [x] 취소하면 서버에 데이터가 전송되지 않음. 
### 1-3
- [x] 글자수 제한 범위(500자)이내 경우만 전송 버튼을 활성화한다.
  - [x] 한글기준으로 500자 이내여야함.(띄어쓰기 포함) 
### 1-4
- [x] 내용 입력 후 등록 버튼을 누르면 새로운 카드가 등록 되고, 내용을 서버로 전달한다.
### 1-5
- [x] 서버에서 응답이 성공하면 입력 화면을 닫는다.
### 1-6
- [ ] 서버에서 응답이 실패면 실패 안내를 표시하고, 다시 시도하도록 한다.
  - [ ] 실패 문구와 재시도 횟수를 표시해줌.
### 1-7
- [x] 서버에 성공적으로 보낸 경우는 목록 화면을 갱신해서 할 일을 표시한다.
  - [ ] 목록 전체 데이터를 다시 받아오지않고 해당 데이터만 받아옴.

**Comment by JiminKim-dev** [comment]
![addBtn](https://user-images.githubusercontent.com/85747667/162390982-5f044b8a-8fb4-499f-b224-15d8e550a755.gif)
![카드등록](https://user-images.githubusercontent.com/85747667/163133614-59220696-c0dc-4a74-ba17-8486fcdb6b6f.gif)
