### ISSUE TITLE
[스토리2] - X버튼 클릭으로 카드 삭제

### ISSUE THREAD

**Issue by dlwnstjrzz** [dlwnstjrzz/todo-list#9]
## 구현하려는 기능
- [x] 유저는 x버튼을 클릭해서 카드를 삭제할 수 있다.

### 2-1
- [x] 카드의 X버튼에 마우스를 올리면 카드가 빨간색으로 변한다.
  - [x]  500ms이상 마우스를 올렸을 시에만 이벤트가 발생함.
### 2-2
- [x] X버튼을 누르면 알림창이 뜬다.
  - [ ] 튀어나오는 애니메이션으로 구현함.
### 2-3 
- [x] 취소 버튼을 누르면 알림창이 닫힌다.
  - [x]  취소하면 서버에 요청을 보내지 않음.
### 2-4
- [x] 삭제 버튼을 누르면 해당 카드 데이터가 서버에서 삭제된다.
### 2-5
- [x] 서버에서 처리가 완료되면 알림창을 닫고 카드를 삭제한다.
  - [x] 해당 컬럼 데이터만 다시 받아와서 렌더링함.

**Comment by JiminKim-dev** [comment]
![디바운싱](https://user-images.githubusercontent.com/85747667/163131322-cc6bc93d-ff22-46c3-8baa-2130b43f6678.gif)
